icon: assets/icons/icon.png
summary: An application to stream Music
group: Application/Multimedia
vendor: Ashish7411
packager: Ashish7411
license: GPLv3
url: https://github.com/Ashish7411/Popkin-player

requires:
  - mpv-libs
  - libappindicator

display_name: Popkin player

keywords:
  - Opensource
  - Music
  - Streaming
  - Flutter

generic_name: Music Application

categories:
  - Music

startup_notify: true